// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGEM013VHsuvJANiCEGt5BFXyJJv6sKWg',
    appId: '1:65118369510:web:f812b533e02ec91480ed27',
    messagingSenderId: '65118369510',
    projectId: 'smart-route-7b87a',
    authDomain: 'smart-route-7b87a.firebaseapp.com',
    storageBucket: 'smart-route-7b87a.firebasestorage.app',
    measurementId: 'G-NMW0S9VG61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVIWOuV20rd2NgQv58lvqZ0ZsJAOEukOM',
    appId: '1:65118369510:android:789f5763b0ae974980ed27',
    messagingSenderId: '65118369510',
    projectId: 'smart-route-7b87a',
    storageBucket: 'smart-route-7b87a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrxaVoEAylUquOxKRrx4rr04cJNV26LRA',
    appId: '1:65118369510:ios:f502fab45d0b921880ed27',
    messagingSenderId: '65118369510',
    projectId: 'smart-route-7b87a',
    storageBucket: 'smart-route-7b87a.firebasestorage.app',
    iosBundleId: 'com.example.smartRoute',
  );
}
